language: c

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/conda
    - source ~/conda/bin/activate
    - conda create -n mppnccombine-fast-build gcc openmpi hdf5=1.10.2 libnetcdf
    - conda create -n mppnccombine-fast-test openmpi pytest xarray

script:
    - conda activate mppnccombine-fast-build; make mppnccombine-fast
    - conda activate mppnccombine-fast-test; make test
