language: c

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/conda
    - source ~/conda/bin/activate
    - conda create --yes -c conda-forge -n build openmpi 'hdf5>=1.10.2' libnetcdf nomkl pytest netcdf4 xarray

script:
    - conda activate build
    - make mppnccombine-fast
