name: Build
on:
  pull_request:
jobs:
  ci:
    name: CI
    uses: access-nri/build-ci/.github/workflows/ci.yml@v4
    with:
      spack-manifest-path: .github/build-ci/manifests/spack.yaml.j2
      allow-ssh-into-spack-install: false
      # Default args (including explicit spack/spack-config versions)
      # are specified in https://github.com/ACCESS-NRI/build-ci/tree/v4/.github/workflows#inputs
